id: AA853758C
title: A Prayer to Recognize My Own Faults and Keep in Mind the Objects of Refuge
type: translation
pechas:
- IEF7D74ED
- I81B703EF
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:48:46.411343
  last_modified_at: 2023-01-04 11:48:46.411354
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IEF7D74ED/F728: '9371'
  I81B703EF/BEBC: '9371'
